[IOPAE-296] add postgres
pagopa/io-services-cms pull request #13
Opened 2023-04-21 13:57 UTC by rodoviti

add postgres flexible server

#### List of Changes

- add keyvault
- add snet for pg
- add pg flexible

#### Motivation and Context

A relational DB is required in order to store all service review requests (see [DR - Review Manager](https://pagopa.atlassian.net/wiki/spaces/IOPAE/pages/674071029/DR+-+Review+Manager) for more info)

#### How Has This Been Tested?

neither a plan nor an apply was executed

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the README (execute pre-commit).

2023-04-26 13:07 UTC, balanza requested changes

2023-04-27 08:06 UTC, rodoviti commented on infra/src/database_review.tf
> +  administrator_password = "Password123!"
fix with 98c1b3c74d2ec03052c74a48f59b0d29c3131848

2023-04-28 09:48 UTC, balanza commented
Updates:
* Postgres admin password is auto-generated (and stored in the key vault)
* common private link and dns zone is used
* docs are updated

2023-04-28 09:48 UTC, balanza approved these changes

2023-04-28 09:48 UTC, merged