[#IOPAE-492]Add legacy status to jira client
pagopa/io-services-cms pull request #282
Opened 2023-07-31 09:53 UTC by StefanoDoc

Add legacy status to jira client
#### List of Changes

#### Motivation and Context

we need to save on the legacy pending table the legacy ticket that have different status from the one in the new jira board , so we can use the same poller that we use for the cms jira board 
#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-07-31 10:22 UTC, rodoviti requested changes

2023-07-31 10:22 UTC, rodoviti commented on apps/io-services-cms-webapp/src/lib/clients/jira-client.ts
> +// import { JiraLegacyIssueStatus } from "./jira-legacy-client";
```suggestion
```

2023-07-31 10:22 UTC, rodoviti approved these changes

2023-08-01 08:17 UTC, giuseppedipinto approved these changes

2023-08-01 08:22 UTC, merged