feat: [IOPAE-315] setup timerTrigger fb for service review checker (poller)
pagopa/io-services-cms pull request #50
Opened 2023-05-11 15:21 UTC by rodoviti

Create a timeTrigger function and its entryPoint in order to check the status to all pending reviews

#### List of Changes

- add timerTrigger config
- add timerTrigger entryPoint

#### Motivation and Context

To check all Jira ticket updates related to all pending review

#### How Has This Been Tested?

no test for "config" code

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-05-11 17:08 UTC, balanza requested changes
* we need to configure `SERVICE_REVIEW_CHECKER_SCHEDULE` otherwise the app would break
* consider disable the handler so that it doesn't run until we are ready
```
"AzureWebJobs.ServiceReviewChecker.Disabled" = "1"
```

2023-05-15 11:26 UTC, giuseppedipinto approved these changes
LGTM

2023-05-15 15:17 UTC, balanza requested changes

2023-05-15 15:17 UTC, balanza commented on apps/io-services-cms-webapp/ServiceReviewChecker/function.json
> +  "disabled": true,
Unfortunately, this flag doesn't work (although docs are not clear about it). The safest method to disable the function is to add this to application settings:
```
"AzureWebJobs.ServiceReviewChecker.Disabled" = "1"
```

2023-05-15 15:22 UTC, balanza approved these changes
I've added and applied this configuration to disable the function to start: https://github.com/pagopa/io-services-cms/pull/50/commits/5735c341367d2624af22fdaf9696462f9a19d409

We can merge and hence publish when we are ready

2023-05-15 15:26 UTC, merged